### ISSUE TITLE
cannot get package to load in R 4.0.4 (2021-02-15)

### ISSUE THREAD

**Issue by sam-a-levy** [ggrothendieck/gsubfn#6]
Hi there!

I have recently switched laptops and am on the version 4.0.4 of R and although `install.packages("gsubfn")` installs the package when I try to call the package from my library or to call gsubfn via `gsubfn::gsubfn()` R gets stuck running a process for an insane amount of time (I gave up at 30 mins). Do you have any idea what the problem could be? Is there some dependency that I am unaware of?

Many thanks

**Comment by ggrothendieck** [comment]
I am unable to reproduce this on Windows 10 and it passes all checks on all systems:  https://cran.r-project.org/web/packages/gsubfn/index.html

If people have problems it is usually that they are using a non-standard version of R that they built themselves that does not have tcltk capability -- that package is used by gsubfn.  Note that if R was not built with that capability then you can't add it later.  You must rebuild R with it from the start or use one of the standard distributions, all of which include it since it is a base package.  `capabilities()` will report which capabilities your build has.

**Comment by sam-a-levy** [comment]
Thanks for this information. My R set up is possibly not conventional, it was provided on the computer by my institution. However, when I run `capabilities("tcltk")` I get the following:

```> capabilities("tcltk")
tcltk 
 TRUE

**Comment by ggrothendieck** [comment]
Not reproducible.  Likely caused by non-standard build, not by gsubfn.
